### ISSUE TITLE
General dependency update

### ISSUE THREAD

**Issue by gomezgoiri** [RusticiSoftware/TinCanJava#52]
Most of the current dependencies use quite old versions:

 *  [JUnit 4.11](http://mvnrepository.com/artifact/junit/junit) was released on November 2012.
 * The [Jackson version](http://mvnrepository.com/artifact/com.fasterxml.jackson.core/jackson-core) (2.1.4) currently used was released on __February 2013__.
 * Apache Commons Codec v1.7 was released on __September 2012__. 
 * The [Joda time](http://mvnrepository.com/artifact/joda-time/joda-time) library used was released in __February 2012__. Furthermore, from Java SE 8 onwards, users are asked to migrate to java.time (JSR-310).
 * (The Jetty client is also outdated in the current version, but hopefully it will be [updated soon](https://github.com/brianjmiller/TinCanJava/tree/jetty9))

So, would not be convenient to update these?

**Comment by brianjmiller** [comment]
This is an ongoing need, but I'm going to close this issue as I think they've all been bumped since the versions listed. Feel free to open another issue/pull request when there is an important update to a dependency, recognizing that we have to maintain backwards compatibility within major versions.
