### ISSUE TITLE
Compilation Errors throughout the project

### ISSUE THREAD

**Issue by tckeith** [RusticiSoftware/TinCanJava#59]
I've cloned the repository in order to create a artifact to use. I've imported the project into the Eclipse IDE and can see that the project is full of compilation errors such as object properties being used without getters and setters: see attached image for example. Is this expected or have I done something wrong?

By default I'm checked out to the master branch, but even when checking out the different version tags the errors still remain.

![image](https://cloud.githubusercontent.com/assets/14043331/21893701/3a59f272-d8aa-11e6-8f58-ade3dd170e98.png)

**Comment by brianjmiller** [comment]
This is because we're using a pre-compilation code generation process that adds simple code bits like constructors/getters/setters, etc. See https://projectlombok.org. I'm not sure how to improve the Eclipse situation, for Intellij there is a plugin that allows it to understand the annotations, etc. For Eclipse see https://projectlombok.org/download.html.

**Comment by tckeith** [comment]
Thank you! Knowing that I was able to get lombok integrated with Eclipse base on the documentation. Working perfectly now!

**Comment by brianjmiller** [comment]
👍
